# Parcel Transformer for Spritesheets

This transformer handles spritesheets as generated by tools like Texture Packer, for use with PixiJS.

To include it, add the following to your `.parcelrc`:

```json
{
  "extends": ["@parcel/config-default"],
  "transformers": {
    "images/*.json": ["parcel-transformer-spritesheet"]
  },
  "packagers": {
    "*.json": "@parcel/packager-raw-url"
  }
}
```

In your game or app, you can then include spritesheets like so:

```js
const interfaceImages = new URL("../images/interface.json", import.meta.url);
await PIXI.Assets.load({
  alias: ["interface"],
  src: interfaceImages.pathname,
});
```
